services:
  app:
    build: .
    image: primary-sales-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - prisma-db:/usr/src/app/prisma/
      - ./.env:/usr/src/app/.env
    environment:
      NODE_ENV: development

volumes:
  prisma-db:
